### ISSUE TITLE
CSS redundante (.point)

### ISSUE THREAD

**Issue by IsTheJack** [ricardodeoliveiradev/Layout-Instagram-HTML5-e-CSS3#1]
No css `ESTILO/estilo.css`, há código repetido desnecessariamente (linhas 32 até 48 ):

```css
.point1 {
    width: 31px;
    height: 31px;
    border-radius: 31px;
    margin-right: 8px;
    background-color: #E0E5F1;
}  

.point2 {
    width: 31px;
    height: 31px;
    border-radius: 31px;
    margin-right: 8px;
    background-color: #E0E5F1;  
}

.point3 {
     width: 31px;
    height: 31px;
    border-radius: 31px;
    background-color: #E0E5F1;
}
```

E no html está assim:

```html
            <div class="point1">

            </div>

            <div class="point2">

            </div>

            <div class="point3">

            </div>
```

Todos estes podem ser simplesmente uma classe `.point` e reutilizados no html, já que têm o mesmo estilo.
